# Generated by Django 3.2.9 on 2022-05-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocks', models.BooleanField(default=True, verbose_name='Состояие шкафа')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Шкафы',
                'verbose_name_plural': 'Шкафы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tarif', models.CharField(max_length=255, verbose_name='Имя Тарифа')),
                ('time_active', models.IntegerField(verbose_name='Срок активности')),
                ('bye', models.FloatField(verbose_name='Цена')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Количество денег')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_param', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тариф',
                'ordering': ['id', 'bye'],
            },
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_train', models.CharField(db_index=True, max_length=255, verbose_name='Название тренажора')),
                ('statuss', models.BooleanField(default=True, verbose_name='Состояние тренажёра')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тренажёры',
                'verbose_name_plural': 'Тренажёры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Фио')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания абонеменнта')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='время последнего посещения')),
                ('num_scaf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.scaf', verbose_name='Номер занимаемого шкафа')),
                ('tarif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.tarif', verbose_name='тариф')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.trainer', verbose_name='тренажёр')),
            ],
            options={
                'verbose_name': 'Посетители',
                'verbose_name_plural': 'Посетители',
                'ordering': ['name', 'time_create'],
            },
        ),
    ]
